### ISSUE TITLE
Intermittent power supply I2C problems can generate thousands of error logs

### ISSUE THREAD

**Issue by spinler** [openbmc/witherspoon-pfault-analysis#3]
The power supply monitoring code will only report a hard I2C error once, but if it starts working again and the fails again, it will then re-report it.  We need to make a change to only report it once total per power on.

**Comment by spinler** [comment]
@bjwyman For some reason I can't seem to assign this to you.

**Comment by bjwyman** [comment]
I cannot self-assign this either. There must be some GitHub permissions/ACL thing that needs updating.

**Comment by bjwyman** [comment]
The problem that lead to this issue getting updated was not a problem with the power supply monitor application, it was the hwmon application for the input power, etc.

The system was using a build that was missing some systemd restart changes.

That problem should be fixed.
Change-Id: I0e5bb3f32022cdb72d00f1a861a69653ef937cf1

https://github.com/openbmc/openbmc/commit/1b3762aeea3f6a41c95a0f94a674121ea6118cc5
